name = "vamos-quiz-server"
main = "src/index.ts"
compatibility_date = "2026-06-01"

[[durable_objects.bindings]]
name = "QuizRoom"
class_name = "QuizRoom"

[[durable_objects.bindings]]
name = "UserStore"
class_name = "UserStore"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["QuizRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["UserStore"]
